Add junos_lacp_interfaces module implementation
ansible/network pull request #29
Opened 2019-07-03 09:42 UTC by ganeshrn

*  Module implementation with merge, delete, replace, override
*  Implement gathering lacp_interfaces facts

2019-07-04 14:39 UTC, danielmellado commented on module_utils/network/junos/config/lacp_interfaces/lacp_interfaces.py
> +import q
I guess this is not inteded to be imported in the final revision ;)

2019-07-04 14:41 UTC, danielmellado requested changes
Just some minor leftover there

2019-07-04 14:44 UTC, danielmellado commented on module_utils/network/junos/config/lacp_interfaces/lacp_interfaces.py
> +import q
Besides that, we should deff agree and merge on tox.ini flake8 validations for this repo. IMHO we should just match ansible/ansible for now

2019-07-29 06:44 UTC, ganeshrn commented
Moved to https://github.com/ansible/ansible/pull/59708

2019-07-29 06:44 UTC, closed without merging